name: flutter_map_heatmap
description: A heatmap plugin for flutter_map
repository: https://github.com/tprebs/fluttermap_heatmap
version: 0.0.4

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^1.0.4